@startuml

left to right direction

package Actores_internos{
actor "Administrador"           as act_1
actor "Coordinador de rutas"    as act_2 #yellow
actor "Contable"                as act_3
actor "Jefe de almacén"         as act_4
}

rectangle Seguridad{
useCase "Identificarse" as (Identificarse) #yellow
useCase "Introducir usuario" as (Introducir_usuario)
useCase "Consultar usuario" as (Consultar_usuario)
useCase "Modificar usuario" as (Modificar_usuario)
useCase "Eliminar usuario" as (Eliminar_usuario)
}

rectangle Entorno{
    
useCase "Generar ruta"  as (Generar_ruta) #yellow
useCase "ingresar datos de ruta" as (ingresar_datos_ruta) #yellow
useCase "verificar ruta" as (verificar_ruta) #yellow


useCase "Modificar ruta" as (Modificar_ruta) #yellow
useCase "Seleccionar ruta" as (Seleccionar_ruta) #yellow
useCase "Eliminar ruta" as (Eliminar_ruta) #yellow
useCase "Consultar ruta"  as (Consultar_ruta) #yellow
useCase "Modificar ruta seleccionada" as (Modificar_ruta_seleccionada) #yellow

useCase "Generar factura" as (Generar_factura)
useCase "Ingresar datos factura" as (Ingresar_datos_factura)

useCase "Modificar factura" as (Modificar_factura)
useCase "Seleccionar factura" as (Seleccionar_factura)

useCase "Eliminar factura" as (Eliminar_factura)


useCase "Consultar factura" as (Consultar_factura)
useCase "Modificar factura seleccionada" as (Modificar_factura_seleccionada)

useCase "Generar empaquetado" as (Generar_empaquetado)
useCase "Ingresar productos al empaquetado" as (Ingresar_producto_al_empaquetado)
useCase "verificar empaquetado" as (Verificar_empaquetado)
useCase "confirmar operación" as (Confirmar_operacion) #yellow


useCase "Modificar empaquetado" as (Modificar_empaquetado)
useCase "Seleccionar empaquetado" as (Seleccionar_empaquetado)
useCase "Seleccionar producto del empaquetado" as (Seleccionar_producto_de_empaquetado)
useCase "Modificar producto del empaquetado" as (Modificar_producto_de_empaquetado)


useCase "Eliminar empaquetado" as (Eliminar_empaquetado)
useCase "Confirmar eliminación" as (Generar_empaquetado1) #yellow


useCase "Consultar empaquetado" as (Consultar_empaquetado)

Generar_empaquetado --> Ingresar_producto_al_empaquetado
Ingresar_producto_al_empaquetado --> Verificar_empaquetado
Ingresar_producto_al_empaquetado ----> Ingresar_producto_al_empaquetado
Verificar_empaquetado -----> Confirmar_operacion

Modificar_empaquetado --> Seleccionar_empaquetado
Seleccionar_empaquetado --> Seleccionar_producto_de_empaquetado
Seleccionar_producto_de_empaquetado --> Modificar_producto_de_empaquetado
Modificar_producto_de_empaquetado -----> Confirmar_operacion
Eliminar_empaquetado --> Seleccionar_empaquetado
Seleccionar_empaquetado --> Generar_empaquetado1

Consultar_empaquetado --> Seleccionar_empaquetado
}

act_1 -[#white]-> act_2
act_1 -[#white]-> act_3
act_1 -[#white]-> act_4
act_1 -[#white]-> Identificarse
act_1 -[#white]-> Consultar_usuario
act_1 -[#white]-> Modificar_usuario
act_1 -[#white]-> Eliminar_usuario
act_1 -[#white]-> Introducir_usuario

act_4 -[#white]-> Generar_empaquetado
act_4 -[#white]-> Modificar_empaquetado
act_4 -[#white]-> Eliminar_empaquetado
act_4 -[#white]-> Consultar_empaquetado
act_4 -[#white]-> Identificarse

act_2 --> Generar_ruta
act_2 -->   Modificar_ruta
act_2 -->   Eliminar_ruta
act_2 -->   Consultar_ruta
act_2 -->   Identificarse

act_3 -[#white]->   Generar_factura
act_3 -[#white]->   Modificar_factura
act_3 -[#white]->   Eliminar_factura
act_3 -[#white]->   Consultar_factura
act_3 -[#white]->   Identificarse

Generar_ruta --> ingresar_datos_ruta
ingresar_datos_ruta --> verificar_ruta
verificar_ruta -----> Confirmar_operacion

Consultar_ruta --> Seleccionar_ruta
Eliminar_ruta --> Seleccionar_ruta
Modificar_ruta --> Seleccionar_ruta
Seleccionar_ruta --> Generar_empaquetado1
Seleccionar_ruta --> Modificar_ruta_seleccionada
Modificar_ruta_seleccionada -----> Confirmar_operacion

Generar_factura -----> Ingresar_datos_factura
Ingresar_datos_factura --> Confirmar_operacion
Modificar_factura --> Seleccionar_factura
Eliminar_factura --> Seleccionar_factura
Seleccionar_factura --> Generar_empaquetado1
Consultar_factura --> Seleccionar_factura
Seleccionar_factura --> Modificar_factura_seleccionada
Modificar_factura_seleccionada -----> Confirmar_operacion

package Actores_externos{
actor "Operador externo" as act_5

}

act_5 ---[#white]-----> Consultar_factura
act_5 ---[#white]-----> Consultar_empaquetado
act_5 ---[#white]-----> Consultar_ruta


@enduml